sudo: required

git:
  depth: 3

services:
  - docker

# A build on Travis CI is made up of two steps:
#    install: install any dependencies required
#    script: run the build script

install:
  - docker build --tag guillaume-florent/corelib:latest .

#  A job fails if the return code of the script phase is non zero.
script:
  - docker run --name corelib guillaume-florent/corelib:latest /bin/bash -c "cd /opt/corelib;pytest tests/"

after_script:
  - docker images