package:
  name: corelib
  version: "0.2.11"

source:
  path: ../corelib

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt
  include_recipe: True

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - jinja2
    - psutil

test:
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests/

about:
  home: https://github.com/guillaume-florent/corelib
  license: MIT
  license_file: LICENSE.txt
  summary: Common Python functions and idioms and units converter