package:
  name: corelib
  version: "0.2.5"

source:
  path: ../corelib
  # git_rev: master
  # git_url: https://github.com/guillaume-florent/corelib.git

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - jinja2
    - psutil

test:
  imports:
    - corelib

about:
  home: https://github.com/guillaume-florent/corelib
  license: MIT
  license_file: LICENSE.txt